// DATABASE LOKASI VILLA
const daftarVilla = [
    { id: 1, nama: "Alaya" },
    { id: 2, nama: "Gunawan" },
    { id: 3, nama: "Maris" },
    { id: 4, nama: "Putih" },
    { id: 5, nama: "Yudistira" },
    { id: 6, nama: "You & Me"},
    { id: 7, nama: "Bumi Ratu"},
    { id: 8, nama: "Bumi Ami"},
    { id: 9, nama: "Aminara"},
    { id: 10, nama: "Lemon"},
    { id: 11, nama: "Puri"},
    { id: 12, nama: "Savira"},
    { id: 13, nama: "Bola Popu"},
    { id: 14, nama: "Kaca 1"},
    { id: 15, nama: "Kaca 2"},
    { id: 16, nama: "Kaca 3"},
    { id: 17, nama: "Kaca 4"},
    { id: 18, nama: "Cabin 1"},
    { id: 19, nama: "Cabin 2"},
    { id: 20, nama: "Pm 1"},
    { id: 21, nama: "Pm 2"},
];

// DATABASE LAYANAN (MENU & SEWA)
const daftarLayanan = [
    // --- KATEGORI: MAKANAN (KULINER) ---
    {
    id: 101,
    nama: "Rice Bowl Chicken Sambal Matah",
    kategori: "makanan",
    harga: "Rp 20.000",
    deskripsi: "???", 
    // gambar: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=500&q=80",
    gambar: "assets/img/Makanan/Ricebowl_A_sambal_matah.jpeg",
    },
    {
        id: 102,
        nama: "Rice Bowl Chicken Sambal Ijo",
        kategori: "makanan",
        harga: "Rp 20.000",
        deskripsi: "Mie goreng khas Jawa dengan sayuran segar dan bakso ayam.",
        // gambar: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400",
        gambar: "assets/img/Makanan/Ricebowl_A_sambal_ijo.jpeg",
    },
    {
        id: 103,
        nama: "Rice Bowl Chicken Karage",
        kategori: "makanan",
        harga: "Rp 20.000",
        deskripsi: "Ayam bakar bumbu madu disajikan dengan sambal terasi dan lalapan.",
        // gambar: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=400",
        gambar: "assets/img/Makanan/Ricebowl_A_karage.jpeg",
    },
    {
        id: 104,
        nama: "Rice Bowl Chicken Asam Manis",
        kategori: "makanan",
        harga: "Rp 20.000",
        deskripsi: "Sayuran segar tumis dengan kuah kaldu ringan dan potongan ayam.",
        // gambar: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=400",
        gambar: "assets/img/Makanan/Ricebowl_A_asam_manis.jpeg",
    },
    {
        id: 105,
        nama: "Nasi Goreng Telur Mata Sapi",
        kategori: "makanan",
        harga: "Rp 20.000",
        deskripsi: "Nasi putih hangat dengan pilihan lauk ayam goreng tepung renyah.",
        // gambar: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=400",
        gambar: "assets/img/Makanan/Nasi_goreng.jpeg",
    },
    {
        id: 106,
        nama: "Mie Tek-Tek Spesial",
        kategori: "makanan",
        harga: "Rp 20.000",
        deskripsi: "Mie goreng khas Jawa dengan sayuran segar dan bakso ayam.",
        gambar: "assets/img/Makanan/Mie_tek-tek.jpeg",
    },
    {
        id: 107,
        nama: "Ayam Kremes",
        kategori: "makanan",
        harga: "Rp 25.000",
        deskripsi: "Ayam goreng tepung renyah dengan kremesan gurih khas Indonesia.",
        gambar: "assets/img/Makanan/Ayam_kremes.jpeg",
    },
    {
        id: 108,
        nama: "Ayam Bakar",
        kategori: "makanan",
        harga: "Rp 25.000",
        deskripsi: "Ayam bakar bumbu madu disajikan dengan sambal terasi dan lalapan.",
        gambar: "assets/img/Makanan/Ayam_bakar.jpeg",
    },

    // --- KATEGORI: JUNKFOOD ---
    {
        id: 201,
        nama: "Mix Snack Platter",
        kategori: "snack",
        harga: "Rp 25.000",
        deskripsi: "Piring berisi campuran keripik kentang, kacang, dan camilan ringan lainnya.",
        gambar: "assets/img/Snack/Mix_platter.jpeg",
    },
    {
        id: 202,
        nama: "Risol Sayur",
        kategori: "snack",
        harga: "Rp 15.000",
        deskripsi: "Risol goreng isi sayuran segar dengan",
        gambar: "assets/img/Snack/Risol_sayur.jpeg",
    },

    // --- KATEGORI: MINUMAN (COFFEE/NON-COFFEE) ---
    {
        id: 301,
        nama: "Americano Ice",
        kategori: "minuman",
        harga: "Rp 23.000",
        deskripsi: "Espresso dengan tambahan air dingin, menyegarkan dan ringan.",
        gambar: "assets/img/Minuman/Americano.jpeg",
    },
    {
        id: 302,
        nama: "Caramel Macchiato Ice",
        kategori: "minuman",
        harga: "Rp 25.000",
        deskripsi: "Espresso dengan susu dingin dan sirup karamel manis.",
        gambar: "assets/img/Minuman/Caramel_macchiato.jpeg",
    },
    {
        id: 303,
        nama: "Dancow Coklat",
        kategori: "minuman",
        harga: "Rp 15.000",
        deskripsi: "Susu Dancow rasa coklat yang lezat dan menyehatkan.",
        gambar: "assets/img/Minuman/Dancow_coklat.jpeg",
    },
    {
        id: 304,
        nama: "Dancow Putih",
        kategori: "minuman",
        harga: "Rp 15.000",
        deskripsi: "Susu Dancow rasa original yang lezat dan menyehatkan.",
        gambar: "assets/img/Minuman/Dancow_putih.jpeg",
    },
    {
        id: 305,
        nama: "es Teh Manis",
        kategori: "minuman",
        harga: "Rp 10.000",
        deskripsi: "Teh manis dingin yang menyegarkan.",
        gambar: "assets/img/Minuman/Es_teh.jpeg",
    },
    {
        id: 305,
        nama: "Jus Buah Naga",
        kategori: "minuman",
        harga: "Rp 17.000",
        deskripsi: "Jus segar dari buah naga merah yang kaya antioksidan.",
        gambar: "assets/img/Minuman/Jus_buah_naga.jpeg",
    },
    {
        id: 306,
        nama: "Jus Pisang",
        kategori: "minuman",
        harga: "Rp 17.000",
        deskripsi: "Jus segar dari pisang pilihan yang manis dan lezat.",
        gambar: "assets/img/Minuman/Jus_pisang.jpeg",
    },
    {
        id: 307,
        nama: "Jus Mangga",
        kategori: "minuman",
        harga: "Rp 17.000",
        deskripsi: "Jus segar dari mangga harum manis yang legit.",
        gambar: "assets/img/Minuman/Jus_mangga.jpeg",
    },
    {
        id: 308,
        nama: "Palm Sugar",
        kategori: "minuman",
        harga: "Rp 25.000",
        deskripsi: "Minuman tradisional manis dari gula aren asli.",
        gambar: "assets/img/Minuman/Palm_sugar1.jpeg",
    },
    {
        id: 309,
        nama: "Pop Ice Jelly",
        kategori: "minuman",
        harga: "Rp 10.000",
        deskripsi: "Minuman serbuk rasa buah dengan tambahan jelly kenyal.",
        gambar: "assets/img/Minuman/Pop_ice.jpeg",
    },
    {
        id: 310,
        nama: "Vanilla Latte Ice",
        kategori: "minuman",
        harga: "25.000",
        deskripsi: "Espresso dengan susu dingin dan sirup vanilla harum.",
        gambar: "assets/img/Minuman/Vanilla_latte.jpeg",
    },

    // --- KATEGORI: PENYEWAAN ALAT ---
    {
        id: 401,
        nama: "Amenities Kit",
        kategori: "sewa",
        harga: "Rp 50.000",
        deskripsi: "Handuk,Sikat gigi, pasta gigi, sabun mandi, dan shampoo dalam kemasan travel size.",
        gambar: "assets/img/Sewa/Amenities.jpeg",
    },
    {
        id: 402,
        nama: "Floaties Pelampung Kolam",
        kategori: "sewa",
        harga: "Rp 50.000",
        deskripsi: "Pelampung kolam renang berbentuk unik untuk bersantai di air.",
        gambar: "assets/img/Sewa/Floaties.jpeg",
    },
    {
        id: 403,
        nama: "Paket Grill Lengkap",
        kategori: "sewa",
        harga: "Rp 200.000",
        deskripsi: "Paket lengkap alat barbeque termasuk panggangan, arang, alat pemanggang, dan peralatan makan.",
        gambar: "assets/img/Sewa/Paket_grill.jpeg",
    },
    {
        id: 404,
        nama: "Paket Bakar 1 (Ayam Bakar)",
        kategori: "sewa",
        harga: "Rp 150.000",
        deskripsi: "Paket lengkap untuk barbeque ayam bakar, termasuk arang, bumbu, dan peralatan.",
        gambar: "assets/img/Sewa/Paket_1_ayam_bakar.jpeg",
    },
    {
        id: 405,
        nama: "Paket Bakar 2 (Sosis Bakar Dll)",
        kategori: "sewa",
        harga: "Rp 100.000",
        deskripsi: "Paket lengkap untuk barbeque sosis dan jagung bakar, termasuk arang, bumbu, dan peralatan.",
        gambar: "assets/img/Sewa/Paket_2_sosis_dll.jpeg",
    },
    {
        id: 406,
        nama: "Extra Bed Set",
        kategori: "sewa",
        harga: "Rp 35.000",
        deskripsi: "Kasur lipat, bantal, guling, dan selimut untuk tambahan tidur.",
        gambar: "assets/img/Sewa/Extra_bed.jpeg",
    },
    
    // --- KATEGORI: INFORMASI ---
    {
        id: 501,
        nama: "Jam Operasional",
        kategori: "info",
        harga: "Buka 08:00 - 21:00",
        deskripsi: "Pemesanan di luar jam tersebut akan diproses keesokan harinya.",
        gambar: "https://images.unsplash.com/photo-1508962914676-134849a727f0?w=400",
    },
    {
        id: 502,
        nama: "Ketentuan Kerusakan",
        kategori: "info",
        harga: "Patuhi Aturan",
        deskripsi: "Setiap kerusakan alat sewa menjadi tanggung jawab penyewa.",
        gambar: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400",
    }
];